[package]
name = "dcim"
version = "1.7.1"
edition = "2021"
authors = ["43615"]
description = "dc improved - Expanded rewrite of a classic RPN calculator / esoteric programming language"
documentation = "https://github.com/43615/dcim/wiki"
repository = "https://github.com/43615/dcim"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "=0.8.5"
rug = "=1.19.0"
read_input = "=0.8.6"
lazy_static = "=1.4.0"